exchange:
#  api-key: "${EXCHANGE_API_KEY}"
  api-key: 4319e1b9-895f-4157-b584-673bfecac0b6
  variables:
    urls:
      market-data: https://redbrokers-market-data.herokuapp.com
    exchange-url:
      order-url: "${exchange.api-key}/order/"
      one: https://exchange.matraining.com/
      two: https://exchange2.matraining.com/

server:
  port: 8085
